{"uuid": "a72e8f68-0742-41c4-b8fd-7cb28faae117", "children": ["3d20f73f-88d3-4f63-95a0-1bb34daff3d5"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: permission denied\n\n", "trace": "  File \"c:\\users\\陈家敏\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\陈家敏\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\陈家敏\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"c:\\users\\陈家敏\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\_pytest\\python.py\", line 745, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"c:\\users\\陈家敏\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\_pytest\\python.py\", line 674, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\Automation\\UI7\\scripts\\test01.py\", line 5, in setup_class\n    self.driver = webdriver.Firefox()\n  File \"c:\\users\\陈家敏\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 174, in __init__\n    keep_alive=True)\n  File \"c:\\users\\陈家敏\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\users\\陈家敏\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"c:\\users\\陈家敏\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\陈家敏\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1600135413995, "stop": 1600135419249}], "start": 1600135413995, "stop": 1600135419332}